# Generated by Django 3.2 on 2021-04-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('rodne_cislo', models.CharField(max_length=25)),
                ('nazev_postu', models.CharField(max_length=25)),
                ('aktivni', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_klubu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rozhodci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('rodne_cislo', models.CharField(max_length=25)),
                ('telefon', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sezona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_sezony', models.CharField(max_length=25)),
                ('nazev_ligy', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Udalost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_udalosti', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zapasy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaci_skore', models.IntegerField()),
                ('hoste_Skore', models.IntegerField()),
                ('datum_cas', models.DateTimeField()),
                ('domaci_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='domaci_ID', to='HazenaIS.klub')),
                ('hoste_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='hoste_ID', to='HazenaIS.klub')),
                ('rozhodci_rID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HazenaIS.rozhodci')),
            ],
        ),
        migrations.CreateModel(
            name='ZapisZapasu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.CharField(max_length=10)),
                ('hrac_hID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HazenaIS.hrac')),
                ('udalost', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HazenaIS.udalost')),
                ('zapasy_zID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HazenaIS.zapasy')),
            ],
        ),
        migrations.CreateModel(
            name='Vysledky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.IntegerField()),
                ('vyhry', models.IntegerField()),
                ('remizy', models.IntegerField()),
                ('prohry', models.IntegerField()),
                ('vstrelene_branky', models.IntegerField()),
                ('utrzene_branky', models.IntegerField()),
                ('klub_kID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HazenaIS.klub')),
                ('sezona_sID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HazenaIS.sezona')),
            ],
        ),
        migrations.CreateModel(
            name='Kariera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vstupu', models.DateTimeField()),
                ('aktivni', models.BooleanField()),
                ('hrac_hID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HazenaIS.hrac')),
                ('klub_kID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HazenaIS.klub')),
                ('sezona_sID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HazenaIS.sezona')),
            ],
        ),
    ]
