# Generated by Django 3.2 on 2021-04-29 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HazenaIS', '0003_auto_20210426_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kariera',
            name='datum_vstupu',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
