# Generated by Django 3.2 on 2021-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HazenaIS', '0004_alter_kariera_datum_vstupu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrac',
            name='aktivni',
            field=models.BooleanField(default=False),
        ),
    ]
